### ISSUE TITLE
Add helper function to get chrono::DateTime from MonotonicTime

### ISSUE THREAD

**Issue by robamu** [asynchronics/asynchronix#21] opened 2024-03-13 10:17 UTC
What do you think about adding a helper API to retrieve a chrono datetime from a `MonotonicTime` ?
The [chrono::DateTime](https://docs.rs/chrono/latest/chrono/struct.DateTime.html)  is an extremely convenient time format to work with, similar to the Python datetime API. If you think this might be a worthwhile addition, I can open a PR. I have already added something similar in the [spacepackets crate](https://egit.irs.uni-stuttgart.de/rust/spacepackets/src/commit/6f5254bdbda0118a83ccca150e04158b36d9489f/src/time/mod.rs#L290) for a unix timestamp wrapper object.

It would probably make sense to hide this behind a `chrono` feature gate similar to how it was done for `serde`.

**Comment by sbarral** [comment] 2024-03-13 13:21
I guess this could make sense, especially if `MonotonicTime` becomes its own crate.

Thinking loud, here are some things to consider:

- the maintenance effort must be weighted against the benefits given that `chrono` is still pre-1.0 (hence might see breaking changes) and that this can already done (albeit clumsily) with a one-liner without needing to switch an extra feature, i.e. `DateTime::from_timestamp(time.as_unix_secs(37), time.subsec_nanos())`,
- is there a reason to privilege the `chrono` crate over the `time` crates? In any case, for forward compatibility it would be best to name the methods according to the crate (e.g.  `as_chrono_date_time()` -- but for the `time` crate it's harder to find a name that isn't confusing...),
- the method would still need to take leap seconds as argument,
- if we go for this, it would probably make sense to add as well `from_chrono_date_time()`, also with a leap seconds argument.

Please let me know what you think.

**Comment by sbarral** [comment] 2024-03-13 13:52
Not strictly related, but looking at the `spacepackets` crate it looks like the CCSDS time code should be TAI-based and not UTC based (based on a quick look at the spec so I could be wrong, but I'd be surprised if they didn't use a monotonic time stamp).

**Comment by robamu** [comment] 2024-03-13 15:28
- I do not know what the release plan is for chrono or the time library.. I think the effort would be manageable though
- No reason :) `chrono` was one of the first major time libraries which is why I selected it. To be honest, from having a look at the download counts for both libraries, both seem to be used commonly. Maybe I'll even add `time` support to the `spacepackets` library. I like the idea with distinct names. Maybe `as_timelib_date_time()` would work alternatively?
- Yup, leap seconds still need to be accounted for. Possible solution: Ignore timestamps before 1972 or throw an explicit error? I would guess most use-cases use current time and not 1970..

About `spacepackets`: All timecodes except CUC are UTC based. So I definitely need to correct this there..

**Comment by sbarral** [comment] 2024-03-14 07:40
I will be busy today but if you want I can have a look at the `spacepacket`'s fix tomorrow. Just one think that caught my eyes in the tests' comments: there were actually leaps seconds before 1972, but these were not integer numbers. For the particular case of the 1958 epoch, however, AFAIK the number of leap seconds was indeed 0 (by design). Yes, it's all but simple...

**Comment by robamu** [comment] 2024-03-14 09:26
To be honest, I am now also working on refactoring other components of the time library. The `UnixTimestamp` is also planned to have nanosecond precision, so other structures like the CUC timestamp can also be more easily created from a UnixTimestamp.

Incidentally, the structures become identical except the leap second offset with that change. In any case, I will create conversion methods to/from MonotonicTime for the `UnixTimestamp`, especially if `MonotonicTime` goes into its own crate. Another idea I had would be to simply move the `UnixTimestamp` into that new crate as a `UnixTime` struct as well, especially because those two are so similar and do not share a lot of dependencies.. But those are just som ideas..

**Comment by robamu** [comment] 2024-03-16 11:34
I just found another good reason to include `MonotonicTime` in a separate crate: It is actually a type which could be useful on `no_std` systems to track elapsed times where `std::time::Instant` is not available. For cases like this, I used `UnixTimestamp`, which relies on the non-monotonic UNIX time. That would require layering the code so that `alloc` and `std` dependent features are behind a feature gate.

**Comment by sbarral** [comment] 2024-03-17 22:08
(sorry for the late PR review of `spacepackets`, done!).

I agree that the CUC time should not be leap-second aware, especially that the leap offset could become invalid when the `CucTime` is modified by arithmetic operations to a date with a different offset.

Yes, making `MonotonicTime` a `no_std` crate make a lot of sense. I would prefer to keep it really bare-bone though, I think it is always possible to build related structs like `UnixTime` or our seqlocked version of `MonotonicTime` in separate crate with very little penalty (I think the only penalty is the assert in `MonotonicTime::new()` which could be avoided by having access to the private fields, but we can probably live with that).

**Comment by sbarral** [comment] 2024-03-22 19:28
The first candidate version of a standalone and more generic version of `MonotonicTime` with `no-std`, `serde` and `chrono` support is now available at https://github.com/asynchronics/tai-time/.

I will thus close this issue in favor of https://github.com/asynchronics/tai-time/issues/1.

I would be grateful for any feedback before the official release (please use the above new issue).

**Closed by sbarral** 2024-03-22 19:28 UTC
